# Generated by Django 6.0.7 on 2026-09-16 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_custody_expensevoucher'),
        ('parties', '0004_party_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')], max_length=8)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_source', to='accounting.journalentry')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='parties.party')),
                ('party_control_account', models.ForeignKey(help_text='AR or AP control account this voucher posts against.', on_delete=django.db.models.deletion.PROTECT, related_name='party_vouchers', to='accounting.account')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='accounting.voucher')),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.account')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
