# Generated by Django 6.0.7 on 2026-09-16 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_voucher'),
        ('parties', '0004_party_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('date', models.DateField()),
                ('booking_reference', models.CharField(blank=True, default='', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('credited', 'Credited (Cancelled by Credit Note)')], default='draft', max_length=16)),
                ('is_issued', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, default='', help_text='Base64 signature captured at issue time.')),
                ('qr_code_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('credits', models.OneToOneField(blank=True, help_text='The original invoice this Credit Note cancels.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_by', to='accounting.invoice')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.party')),
                ('replaces', models.OneToOneField(blank=True, help_text='The original invoice this replacement re-issues.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='accounting.invoice')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
