# Generated by Django 6.0.7 on 2026-09-16 13:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('pending_receivables', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('pending_payables', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('is_locked', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
