# Generated by Django 6.0.7 on 2026-09-17 12:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_financialperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='custody',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='custody',
            name='due_date',
            field=models.DateField(blank=True, help_text='Deadline by which this custody must be settled.', null=True),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='attachment_data',
            field=models.TextField(blank=True, default='', help_text='Base64 data URL of the uploaded receipt/invoice image.'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='booking_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='vat_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_vat_entries', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='expensevoucher',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
