# Generated by Django 6.0.7 on 2026-09-17 12:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_custody_currency_custody_due_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_recurring_expenses', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expense_bookings', to='accounting.account')),
                ('treasury_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expense_treasury', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
