# Generated by Django 6.0.7 on 2026-09-18 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_recurringexpensetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='attachment_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voucher',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='voucher',
            name='booking_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='voucher',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('instapay', 'InstaPay'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card')], default='cash', max_length=16),
        ),
        migrations.AddField(
            model_name='voucher',
            name='transaction_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
