# Generated by Django 6.0.7 on 2026-09-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_voucher_attachment_data_voucher_attachment_name_and_more'),
        ('bookings', '0005_booking_accounting_journal_entry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='bookings.booking'),
        ),
    ]
