# Generated by Django 6.0.7 on 2026-09-18 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_voucher_booking'),
        ('bookings', '0005_booking_accounting_journal_entry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ar_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_ar', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_source', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revenue_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_revenue', to='accounting.account'),
        ),
    ]
