# Generated by Django 6.0.7 on 2026-08-24 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('target_model', models.CharField(help_text='اسم الموديل المستهدف مثل: Voucher أو Account', max_length=100, verbose_name='Target Model')),
                ('target_object_id', models.CharField(blank=True, help_text='معرف السجل المراد تعديله لو كانت العملية UPDATE/DELETE', max_length=100, null=True, verbose_name='Target Object ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10, verbose_name='Action Type')),
                ('payload', models.JSONField(help_text='بيانات التغيير قبل وبعد بصيغة JSON', verbose_name='Payload')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Checker')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_change_requests', to=settings.AUTH_USER_MODEL, verbose_name='Maker')),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Requests',
                'db_table': 'vv_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
