# Generated by Django 6.0.7 on 2026-08-30 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('access_denied', 'Access Denied (403)'), ('change_submitted', 'Change Submitted'), ('change_applied_direct', 'Change Applied Directly'), ('change_approved', 'Change Approved'), ('change_rejected', 'Change Rejected'), ('change_apply_failed', 'Change Apply Failed')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='changerequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='target_model',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='target_object_id',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='changerequest',
            name='apply_failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='entity_id',
            field=models.CharField(blank=True, help_text='رقم/كود السجل المستهدف. فاضي لو الطلب ده لإنشاء سجل جديد بالكامل.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='entity_type',
            field=models.CharField(default='', help_text="اسم الموديول/الكيان المستهدف — مثال: 'account', 'voucher', 'journal_entry'.", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changerequest',
            name='proposed_data',
            field=models.JSONField(default=dict, help_text='التعديل المقترح كامل — الحقول الجديدة، أو تفاصيل العملية المطلوبة.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changerequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='target_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='checker',
            field=models.ForeignKey(blank=True, help_text='مين وافق/رفض — فاضي لحد ما حد يراجع الطلب فعليًا.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checked_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='maker',
            field=models.ForeignKey(help_text='مين طلب التعديل.', on_delete=django.db.models.deletion.PROTECT, related_name='made_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('apply_failed', 'Apply Failed')], default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_change_entity__6aaf82_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status'], name='core_change_status_63c926_idx'),
        ),
        migrations.AlterModelTable(
            name='changerequest',
            table=None,
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='لو الحساب ده ليه أب في الشجرة. PROTECT مش CASCADE عمدًا — منع حذف أب لسه له فروع، بدل ما تتمسح الفروع صامتة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.account'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='فاضي لو الحدث حصل قبل أي مصادقة (مثال: محاولة login فاشلة باسم مستخدم مش موجود).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type'], name='core_auditl_event_t_04b2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor'], name='core_auditl_actor_i_870709_idx'),
        ),
    ]