# Generated by Django 6.0.7 on 2026-09-20 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(db_index=True, help_text='e.g. Sokhna, Hurghada, Sharm El Sheikh.', max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo_data', models.TextField(blank=True, default='', help_text="Base64 data URL of the hotel's photo.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hotels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['area', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HotelEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='e.g. Reservations, Sales.', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='hotels_directory.hotel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HotelPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='e.g. Reservations, Front Desk.', max_length=100)),
                ('number', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='hotels_directory.hotel')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
