# Generated by Django 6.0.7 on 2026-09-23 23:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0007_booking_customer_booking_original_customer_code'),
        ('parties', '0006_alter_party_client_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('service_type', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('stage', models.CharField(choices=[('stage1', 'New Target'), ('stage2', 'In Contact'), ('stage3', 'Quote/Negotiation'), ('stage4', 'Won'), ('stage5', 'Lost')], db_index=True, default='stage1', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_deal', to='bookings.booking')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='parties.party')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Phone Call'), ('email', 'Email'), ('visit', 'Field Visit')], max_length=16)),
                ('note', models.TextField()),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logged_activities', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales_crm.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage'], name='sales_crm_d_stage_ee5344_idx'),
        ),
    ]
