# Generated by Django 6.0.7 on 2026-09-02 20:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('economy', 'Economy'), ('luxury', 'Luxury'), ('bus', 'Bus'), ('van', 'Van')], default='economy', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='car',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='car',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
