# Generated by Django 6.0.7 on 2026-08-31 01:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_commission', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5)),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('KWD', 'KWD'), ('CAD', 'CAD'), ('CNY', 'CNY'), ('JPY', 'JPY')], default='EGP', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Phone Call'), ('email', 'Email')], max_length=16)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('KWD', 'KWD'), ('CAD', 'CAD'), ('CNY', 'CNY'), ('JPY', 'JPY')], default='EGP', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('department', models.CharField(choices=[('flights', 'Flights'), ('hotels', 'Hotels'), ('packages', 'Packages'), ('visas', 'Visas'), ('transfers', 'Transfers'), ('insurance', 'Insurance')], max_length=16)),
                ('client_name', models.CharField(max_length=255)),
                ('service', models.CharField(blank=True, default='', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('selling', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('KWD', 'KWD'), ('CAD', 'CAD'), ('CNY', 'CNY'), ('JPY', 'JPY')], default='EGP', max_length=3)),
                ('payment_status', models.CharField(choices=[('paid_full', 'Paid in Full'), ('deposit', 'Deposit'), ('unpaid', 'Unpaid')], default='unpaid', max_length=16)),
                ('date', models.DateField()),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['department'], name='sales_sale_departm_d4f16f_idx'), models.Index(fields=['payment_status'], name='sales_sale_payment_f41ab8_idx'), models.Index(fields=['client_name'], name='sales_sale_client__cd6476_idx')],
            },
        ),
    ]
