# Generated by Django 6.0.7 on 2026-09-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_allowed_modules_user_department_user_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('OWNER', 'Owner'), ('IT', 'IT'), ('ACCOUNTANT', 'Accountant'), ('OPERATIONS', 'Operations Staff'), ('SALES', 'Sales Executive')], db_index=True, default='OPERATIONS', max_length=20),
        ),
    ]
