# Generated by Django 6.0.7 on 2026-09-10 13:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partydocument',
            name='party',
        ),
        migrations.RemoveField(
            model_name='partydocument',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='party',
            name='version',
        ),
        migrations.AlterField(
            model_name='party',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='party',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='party',
            name='parent_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_members', to='parties.party'),
        ),
        migrations.AlterField(
            model_name='party',
            name='preferences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='party',
            name='relationship',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='PartyCrmLogEntry',
        ),
        migrations.DeleteModel(
            name='PartyDocument',
        ),
    ]
