# Generated by Django 6.0.7 on 2026-09-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_remove_partydocument_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PartyContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_numbers', to='parties.party')),
            ],
        ),
        migrations.CreateModel(
            name='PartySocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=64)),
                ('handle_or_url', models.CharField(max_length=500)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='parties.party')),
            ],
        ),
    ]
