# Generated by Django 6.0.7 on 2026-09-16 09:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_party_industry_partycontactnumber_partysociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
    ]
