# Generated by Django 6.0.7 on 2026-09-21 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_party_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_party_aliases', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='parties.party')),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
    ]
