# Generated by Django 6.0.7 on 2026-09-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_partyalias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='client_category',
            field=models.CharField(choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('sales_report', 'Sales Report Customer')], max_length=16),
        ),
    ]
