# Generated by Django 6.0.7 on 2026-08-30 23:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('visa', 'Visa')], max_length=16)),
                ('date', models.DateField()),
                ('reference_number', models.CharField(blank=True, default='', help_text='ticketNo (طيران) / invoice (فنادق) / appNo (تأشيرات)', max_length=64)),
                ('service_detail', models.CharField(blank=True, default='', max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('file_number', models.CharField(blank=True, default='', help_text='كود العائلة/الشركة المشترك — TODO: ForeignKey على Party لما B2B/B2C يتبنى في الـBackend', max_length=64)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(choices=[('EGP', 'EGP'), ('USD', 'USD'), ('EUR', 'EUR'), ('SAR', 'SAR'), ('KWD', 'KWD'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('CAD', 'CAD')], default='EGP', max_length=3)),
                ('net_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('handling', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('selling_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('collection_status', models.CharField(choices=[('cash', 'Cash'), ('instapay', 'InstaPay'), ('bank', 'Bank'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='unpaid', max_length=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=16)),
                ('record_status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('posted_to_treasury', models.BooleanField(default=False, help_text='تحصيلات الجنيه بس بتترحّل للخزينة الحقيقية عبر core/treasury (لما يتبنى) — مطابق لمنطق treasury.js.')),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['department'], name='bookings_bo_departm_dbd536_idx'), models.Index(fields=['review_status'], name='bookings_bo_review__a610fb_idx'), models.Index(fields=['collection_status'], name='bookings_bo_collect_af51fe_idx'), models.Index(fields=['file_number'], name='bookings_bo_file_nu_41f23f_idx')],
            },
        ),
    ]
