# Generated by Django 6.0.7 on 2026-09-05 12:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_departm_dbd536_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_review__a610fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_collect_af51fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_file_nu_41f23f_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='booking',
            name='route',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='collection_status',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('instapay', 'InstaPay'), ('bank', 'Bank'), ('partial', 'Partial')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='file_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='posted_to_treasury',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_detail',
        ),
    ]
