# Generated by Django 6.0.7 on 2026-09-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='accounting_journal_entry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='accounting_status',
            field=models.CharField(choices=[('pending', 'Pending Accounting Approval'), ('locked', 'Approved & Locked')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_cancellation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='supplier_cancellation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
