# Generated by Django 6.0.7 on 2026-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_accounting_journal_entry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='department',
            field=models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('visa', 'Visa'), ('car', 'Car')], max_length=16),
        ),
    ]
