# Generated by Django 6.0.7 on 2026-09-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_car_type_booking_driver_name_and_more'),
        ('parties', '0005_partyalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='parties.party'),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_customer_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
